import React, { useEffect, useState, useContext } from 'react';
import styled from 'styled-components';
import { Link as ScrollLink } from 'react-scroll';
import { Link as RouterLink, useNavigate } from 'react-router-dom';
import { Menu, MenuButton, MenuList, MenuItem, Text, useToast } from '@chakra-ui/react';
import { BellIcon } from '@chakra-ui/icons';
import { FaUserCircle } from 'react-icons/fa';
import Logo from '../../../../assets/logo2.png';
import MinistryLogo from '../../../../assets/Ministry AYUSH Logo.png';
import BurgerIcon from '../../assets/svg/BurgerIcon';
import Sidebar from '../Nav/Sidebar';